spring:
  datasource:
    url: jdbc:sqlserver://connectionhtdb.database.windows.net:1433;database=connectiontest;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: connectionhtdb
    password: AzureSQL2023
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191